version: '3' #1
services: #2
  app: #3
    container_name: react_netflix_container #4
    image: node:14-alpine
    volumes:
      - ./:/app #6
    working_dir: /app #7
    command: sh #8
    ports:
      - '3000:3000' #9
    environment:
      - CHOKIDAR_USEPOLLING=true #10
    tty: true